"""Development-gated lifecycle boundaries; normal Frappe actions remain authoritative."""
import json
from copy import deepcopy
import frappe
from privacy_shield.desk import enabled, project_document, prepare_payload, _prepare, _project_response
from privacy_shield.policy import current_capabilities
from privacy_shield.registry import DISPLAY_FIELDS, EXTRA_SENSITIVE_FIELDS
from privacy_shield.guards import preserve_sources


def payload(value):
    value=json.loads(value) if isinstance(value,str) else deepcopy(value)
    if not isinstance(value,dict): raise frappe.ValidationError("Expected a document object")
    return value


def strip_controls(value):
    """Do not accept client flags that bypass normal permission/validation hooks."""
    if isinstance(value,list): return [strip_controls(item) for item in value]
    if not isinstance(value,dict): return value
    return {key:strip_controls(item) for key,item in value.items()
            if key not in {"flags","ignore_permissions","ignore_links","ignore_mandatory",
                           "ignore_version","ignore_validate","__privacy_shield"}}


def prepare_new(data, capabilities):
    data=strip_controls(payload(data))
    dt=data.get("doctype")
    amendment_source = {}
    if data.get("amended_from") and dt in ("Patient Encounter", "Sales Invoice"):
        source = frappe.get_doc(dt, data["amended_from"])
        source.check_permission("read")
        source.check_permission("amend")
        if source.docstatus != 2:
            raise frappe.ValidationError("Only cancelled documents can be amended")
        amendment_source = source.as_dict()
        # Number copies belong to the original party. Resolve a different party
        # in its normal intake workflow instead of retaining the old numbers.
        if not capabilities.edit_original:
            for field in ("patient", "customer", "contact_person"):
                if field in data and data[field] != amendment_source.get(field):
                    raise frappe.PermissionError("Changing the party on an amendment requires number-edit permission")
    if dt == "Clinic Appointment":
        from privacy_shield.appointment_views import prepare_reference
        data = prepare_reference(data, {}, capabilities)
    from privacy_shield.display_text import preserve_display
    try:
        data = preserve_display(data, amendment_source, capabilities.view_full)
    except PermissionError as exc:
        raise frappe.PermissionError(str(exc)) from exc
    except ValueError as exc:
        raise frappe.ValidationError(str(exc)) from exc
    for key in DISPLAY_FIELDS[dt]:
        if data.get(key) in (None, ""): data.pop(key,None)
    try:
        data=preserve_sources(data,amendment_source,DISPLAY_FIELDS[dt],capabilities.edit_original)
        # Blank placeholders from a new form are not number edits.
    except PermissionError as exc:
        raise frappe.PermissionError("Entering original numbers requires number-edit permission") from exc
    except ValueError as exc:
        raise frappe.ValidationError(str(exc)) from exc
    for key in EXTRA_SENSITIVE_FIELDS.get(dt,()):
        if data.get(key) not in (None, "", amendment_source.get(key)):
            raise frappe.PermissionError("Derived phone keys must be generated by the server")
        data.pop(key,None)
        if amendment_source.get(key) is not None:
            data[key] = amendment_source[key]
    for field in DISPLAY_FIELDS[dt].values(): data.pop(field,None)
    if dt=="Contact":
        for row in data.get("phone_nos") or []:
            if not isinstance(row,dict): raise frappe.ValidationError("Invalid phone row")
            if (row.get("parent") not in (None,"",data.get("name"))
                or row.get("parenttype") not in (None,"","Contact")
                or row.get("parentfield") not in (None,"","phone_nos")
                or row.get("doctype") not in (None,"","Contact Phone")):
                raise frappe.PermissionError("New phone row ownership does not match its Contact")
            # Let Frappe assign new child identities; never reuse an existing row ID.
            for key in ("name","parent","parenttype","parentfield"):
                row.pop(key,None)
            row["doctype"]="Contact Phone"
            if row.get("phone") in (None,""): row.pop("phone",None)
            try:
                checked=preserve_sources(row,{},["phone"],capabilities.edit_original)
            except PermissionError as exc: raise frappe.PermissionError(str(exc)) from exc
            except ValueError as exc: raise frappe.ValidationError(str(exc)) from exc
            row.update(checked);row.pop("mask_phone",None)
    return data


def is_scoped(data):
    if data.get("doctype")=="Contact Phone" and enabled("Contact"):
        raise frappe.PermissionError("Create or update phone rows through their Contact")
    return enabled(data.get("doctype"))


@frappe.whitelist(methods=["POST","PUT"])
def insert(doc=None):
    from frappe.client import insert as original
    data=payload(doc)
    if not is_scoped(data): return original(doc)
    capabilities=current_capabilities()
    result=original(prepare_new(data,capabilities))
    return project_document(result,capabilities)


@frappe.whitelist(methods=["POST","PUT"])
def insert_many(docs=None):
    from frappe.client import insert_many as original
    values=json.loads(docs) if isinstance(docs,str) else deepcopy(docs)
    if not isinstance(values,list) or len(values)>200:
        raise frappe.ValidationError("Expected at most 200 documents")
    capabilities=None;prepared=[]
    for value in values:
        data=payload(value)
        if is_scoped(data):
            if capabilities is None: capabilities=current_capabilities()
            data=prepare_new(data,capabilities)
        prepared.append(data)
    return original(prepared)


@frappe.whitelist(methods=["POST","PUT"])
def submit(doc):
    from frappe.client import submit as original
    data=payload(doc)
    if not is_scoped(data): return original(doc)
    capabilities=current_capabilities()
    result=original(_prepare(strip_controls(data),capabilities))
    return project_document(result,capabilities)


@frappe.whitelist(methods=["POST","PUT"])
def cancel(doctype,name):
    from frappe.client import cancel as original
    if not enabled(doctype): return original(doctype,name)
    doc=frappe.get_doc(doctype,name)
    doc.check_permission("read")
    doc.check_permission("cancel")
    capabilities=current_capabilities()
    doc.cancel()
    doc.apply_fieldlevel_read_permissions()
    return project_document(doc.as_dict(),capabilities)


@frappe.whitelist(methods=["POST","PUT"])
def desk_cancel(doctype=None,name=None,workflow_state_fieldname=None,workflow_state=None):
    from frappe.desk.form.save import cancel as original
    if not enabled(doctype): return original(doctype,name,workflow_state_fieldname,workflow_state)
    if workflow_state_fieldname:
        doc=frappe.get_doc(doctype,name)
        if workflow_state_fieldname in set(DISPLAY_FIELDS[doctype]) | set(EXTRA_SENSITIVE_FIELDS.get(doctype,())) | set(DISPLAY_FIELDS[doctype].values()):
            raise frappe.PermissionError("A number field cannot be used as workflow state")
        df=doc.meta.get_field(workflow_state_fieldname)
        if not df or df.fieldtype not in ("Link","Select"):
            raise frappe.ValidationError("Invalid workflow state field")
    capabilities=current_capabilities()
    result=original(doctype,name,workflow_state_fieldname,workflow_state)
    _project_response(capabilities)
    return result


@frappe.whitelist(methods=["POST","PUT"])
def bulk_update(docs):
    from frappe.client import bulk_update as original
    values=json.loads(docs) if isinstance(docs,str) else deepcopy(docs)
    if not isinstance(values,list) or len(values)>200:
        raise frappe.ValidationError("Expected at most 200 updates")
    scoped=any(is_scoped(payload(item)) for item in values)
    if not scoped: return original(json.dumps(values))
    capabilities=current_capabilities()
    prepared=[]
    # Preflight before the first save. HTTP transaction rollback handles save errors.
    for item in values:
        data=strip_controls(payload(item))
        dt=data.get("doctype");name=data.pop("docname",None)
        if not name or (data.get("name") and data["name"]!=name):
            raise frappe.ValidationError("Invalid bulk record identity")
        doc=frappe.get_doc(dt,name)
        doc.check_permission("write")
        data["name"]=name
        if enabled(dt):
            doc.check_permission("read")
            try: data=prepare_payload(data,doc.as_dict(),capabilities)
            except PermissionError as exc: raise frappe.PermissionError(str(exc)) from exc
            except ValueError as exc: raise frappe.ValidationError(str(exc)) from exc
        prepared.append((doc,data))
    for doc,data in prepared:
        doc.update(data)
        doc.save()
    # Never return submitted numbers or exception tracebacks in bulk responses.
    return {"failed_docs":[]}
